Algoritmo "Ex01-Repita"
// Disciplina   : [Lógica de Programação com Visualg]
// Professor   : Jailson Costa dos Santos 
// Descrição   :
// Autor(a)    : Gabriel Lopes dos Santos
// Data atual  : 09/04/2025
Var
// Seção de Declarações das variáveis 

   contador: Inteiro

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc...
   contador <- 0

   Repita
      Escreval("Número: ", contador)
      contador <- contador + 1
   Até contador > 10



Fimalgoritmo